home:dev:   '/auth/login',
home:dev:   '/auth/verify',
home:dev:   '/auth/register',
home:dev:   '/auth/me',
home:dev:   '/auth',
home:dev:   '/listings/seller([^/]*)',
home:dev:   '/listings/seller([^/]*)',
home:dev:   '/listings/seller/my',
home:dev:   '/listings/seller',
home:dev:   '/listings/seller/:id',
home:dev:   '/listings/seller/:id/details',
home:dev:   '/listings/seller/:id/floors',
home:dev:   '/listings/seller/:id/floors/:floorId',
home:dev:   '/listings/seller/:id/floors/:type/rooms/:roomId',
home:dev:   '/listings/seller/:id/rooms/:roomId',
home:dev:   '/listings/seller/:id/rooms/:roomId',
home:dev:   '/listings/seller/:id/gpt/description',
home:dev:   '/listings/seller/:id',
home:dev:   '/listings/seller/:id/terms',
home:dev:   '/listings/seller',
home:dev:   '/listings',
home:dev:   '/addresses([^/]*)',
home:dev:   '/addresses/search',
home:dev:   '/addresses',
home:dev:   '/hooks/stripe',
home:dev:   '/hooks',
home:dev:   '/payments([^/]*)',
home:dev:   '/payments/create',
home:dev:   '/payments',
home:dev:   '/properties/:id/images',
home:dev:   '/properties/:id/images/:id',
home:dev:   '/properties/:id/images'