name: Price Paid - Staging Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    environment: "Staging - Price Paid"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Inject Environment Variables
        run: |
          cd services/price-paid
          touch .env
          echo "DATABASE_URL=${{secrets.STAGING_DATABASE_URL}}" >> .env
          echo "DATA_DATABASE_URL=${{secrets.STAGING_DATA_DATABASE_URL}}" >> .env
          echo "EPC_SECRET=${{secrets.EPC_SECRET}}" >> .env
          echo "EPC_USERNAME=${{secrets.EPC_USERNAME}}" >> .env

      - name: Build & Deploy
        run: pnpm sst:deploy PricePaid --stage=staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"
